@extends('layouts.app')
@section('title', 'Setting - Profile')
@section('route', end($route))

@section('content')
    <x-breadcrumb :route="$route" title="{{ $title }}" />
    <div class="container mx-auto p-4">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-base-text">
            <div class="bg-base-card p-6 rounded-lg shadow-lg">
                <h2 class="text-2xl font-semibold mb-4">
                    Two Factor Setup
                </h2>
                <p class="mb-4">
                    To setup two factor authentication you first need to download Google Authenticator:
                </p>
                <ul class="list-disc list-inside mb-4">
                    <li>
                        <a class="text-primary" href="#">
                            Google Authenticator for Android (Play Store)
                        </a>
                    </li>
                    <li>
                        <a class="text-primary" href="#">
                            Google Authenticator for iOS (Apple App Store)
                        </a>
                    </li>
                </ul>
                <p class="mb-4">
                    Then scan the below barcode or, if you are not able to scan the barcode, you can enter the "Security
                    Key" manually.
                </p>
                <p class="mb-4">
                    <span class="font-semibold">
                        Security Key:
                    </span>
                    <span class="text-primary">
                        FHB2TRGANFYAI45D
                    </span>
                    (Time Based Code)
                </p>
                <img alt="QR Code" class="mb-4" src="https://placehold.co/100x100" />
                <p class="mb-4">
                    Enter the 6 digit code generated by Google Authenticator in the 2FA code box and switch "Enable
                    Two-Factor" to On
                </p>
                <p class="bg-red-600 text-white p-2 rounded inline-block mb-4">
                    Important: Save this secret code for future reference
                </p>
                <p>
                    Note: No Google account is required to use Google Authenticator; skip any Google logins
                </p>
            </div>
            <div class="bg-base-card p-6 rounded-lg shadow-lg">
                <h2 class="text-2xl font-semibold mb-4">
                    Account Security
                </h2>
                <form>
                    <div class="mb-4">
                        <label class="block text-sm font-medium mb-2" for="enable-2fa">
                            Enable 2FA
                        </label>
                        <select class="w-full p-2 bg-base-input border border-gray-600 rounded" id="enable-2fa">
                            <option>
                                Off
                            </option>
                            <option>
                                On
                            </option>
                        </select>
                    </div>
                    <div class="mb-4">
                        <label class="block text-sm font-medium mb-2" for="2fa-code">
                            Enter 2FA Code
                        </label>
                        <input class="w-full p-2 bg-base-input border border-gray-600 rounded" id="2fa-code"
                            type="text" />
                    </div>
                    <button class="w-full bg-primary text-white p-2 rounded" type="submit">
                        Submit
                    </button>
                </form>
            </div>
            <div class="bg-base-card p-6 rounded-lg shadow-lg md:col-span-2">
                <h2 class="text-2xl font-semibold mb-4">
                    Google Authenticator Guide
                </h2>
                <ol class="list-decimal list-inside space-y-2">
                    <li>
                        Install Google Authenticator for Android or Apple and open Google Authenticator
                    </li>
                    <li>
                        Go to
                        <span class="bg-base-input p-1 rounded">
                            Menu
                        </span>
                        -&gt;
                        <span class="bg-base-input p-1 rounded">
                            Setup Account
                        </span>
                    </li>
                    <li>
                        Choose
                        <span class="bg-base-input p-1 rounded">
                            Scan a barcode
                        </span>
                        option, and scan the barcode shown on this page
                    </li>
                    <li>
                        If you are unable to scan the barcode: Choose
                        <span class="bg-base-input p-1 rounded">
                            Enter provided key
                        </span>
                        and type in the "Security Key"
                    </li>
                    <li>
                        A six digit number will now appear in your Google Authenticator app home screen, enter this code
                        into the 2FA form on this page
                    </li>
                    <li>
                        Every time you login to The Systematic Trade you must enter the new 2FA code from your Google
                        Authenticator into the 2FA box on the login form
                    </li>
                    <li>
                        Contact administrator if you want to reset your 2FA Google Authenticator.
                    </li>
                </ol>
            </div>
        </div>
    </div>
@endsection
